/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;
	printf("Solicitud de la operación suma\n");
	result=argp->num1 + argp->num2;
	return &result;
}

float *
resta_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Solicitud de la operación resta\n");
	result=argp->num1 - argp->num2;

	return &result;
}

float *
mult_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Solicitud de la operación multiplicacion\n");
	result=(argp->num1 * argp->num2);

	return &result;
}

float *
div_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Solicitud de la operación division\n");
	result=(argp->num1 / argp->num2);

	return &result;
}
