/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


float
calculadora_1(char *host, float n1,float n2, char opr)
{
	CLIENT *clnt;
	float  *result_1;
	entrada  suma_1_arg;
	float  *result_2;
	entrada  resta_1_arg;
	float  *result_3;
	entrada  mult_1_arg;
	float  *result_4;
	entrada  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

if(opr=='+'){
	suma_1_arg.num1=n1;
	suma_1_arg.num2=n2;
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	} else if (opr=='-')
	{
		resta_1_arg.num1=n1;
		resta_1_arg.num2=n2;
		result_2 = resta_1(&resta_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_2;
	} else if (opr=='*')
	{
		mult_1_arg.num1=n1;
		mult_1_arg.num2=n2;
		result_3 = mult_1(&mult_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_3;
	} else if (opr=='/')
	{	
		div_1_arg.num1=n1;
		div_1_arg.num2=n2;
		if(n2==0){
			printf("dividir sobre cero no es valido \n");
			exit(0);
		}else{
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		return *result_4;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float a,b;
 	char op;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("Tarea 3.1 calculadora distribuida con RPC\n");
	printf("Usar + pasa SUMA\nUsar - para RESTA\nUsar * MULTIPLICAR\nUsar / para DIVIDIR\n");
	printf("Escribe numero 1 :\n");
	scanf("%f",&a);
	printf("Escribe numero 2 :\n");
	scanf("%f",&b);
	printf("Escribe el operador :\n");
	scanf("%s",&op);

	host = argv[1];
	
	
	printf("La respuesta de la operación %f %c %f es: %f \n",a,op,b,calculadora_1 (host,a,b,op));
exit (0);
}
